# Generated by Django 5.0.6 on 2026-06-15 13:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MoveOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=50)),
                ('customer_phone', models.CharField(max_length=30)),
                ('origin', models.CharField(max_length=160)),
                ('destination', models.CharField(max_length=160)),
                ('move_date', models.DateField()),
                ('move_time', models.TimeField()),
                ('items', models.TextField(blank=True)),
                ('note', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', '待抢单'), ('claimed', '已抢单'), ('assigned', '已派单'), ('in_progress', '服务中'), ('completed', '已完成')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_orders', to='workers.worker')),
                ('claimed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='claimed_orders', to='workers.worker')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
