# Generated by Django 5.0.6 on 2026-06-21 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='moveorder',
            name='has_exception',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='moveorder',
            name='service_area',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
    ]
