# Generated by Django 5.0.6 on 2026-06-15 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=30)),
                ('vehicle', models.CharField(max_length=80)),
                ('service_area', models.CharField(max_length=120)),
                ('rating', models.DecimalField(decimal_places=1, default=5.0, max_digits=2)),
                ('status', models.CharField(choices=[('available', '可接单'), ('busy', '服务中'), ('offline', '离线')], default='available', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
