# Generated by Django 5.0.6 on 2026-06-15 13:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        ('workers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgressEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(choices=[('created', '已预约'), ('claimed', '已抢单'), ('assigned', '已派单'), ('departed', '已出发'), ('loading', '装车中'), ('in_transit', '运输中'), ('unloading', '卸货中'), ('completed', '已完成')], max_length=20)),
                ('message', models.CharField(max_length=220)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_events', to='orders.moveorder')),
                ('worker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='workers.worker')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
